name: Daily Contributions

on:
  schedule:
    - cron: '* * * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import --pinentry-mode loopback
          echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --edit-key 75DAEEFD3D85434E trust quit
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Configure git for GPG
        run: |
          git config --global user.signingkey 75DAEEFD3D85434E
          git config --global commit.gpgsign true
          git config --global gpg.program gpg

      - name: Make daily contribution
        run: |
          echo "Making daily contribution"
          echo "$(date)" >> README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Daily contribution"
          add: "README.md"
          signoff: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution
          base: main
          body: "This pull request was created automatically by a GitHub Actions workflow to make a daily contribution."
          token: ${{ secrets.GH_TOKEN }}
